name: CI/CD Pipeline

on:
  push:
    branches:
      - prod

jobs:
  test:
    name: Install and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: '${{ secrets.DOCKER_USERNAME }}/techbuddy:latest'

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/techbuddy:latest

            # Create a Docker Compose file for the production setup
            echo 'version: "3.8"
            services:
              web:
                image: ${{ secrets.DOCKER_USERNAME }}/techbuddy:latest
                ports:
                  - "3000:3000"
                depends_on:
                  - db
                environment:
                  NODE_ENV: production
                  DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/techbuddy
                  JWT_SECRET: ${{ secrets.JWT_SECRET }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

              websocket:
                image: ${{ secrets.DOCKER_USERNAME }}/techbuddy:latest
                command: node server.js
                ports:
                  - "3001:3001"
                depends_on:
                  - db
                environment:
                  NODE_ENV: production
                  DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/techbuddy

              peerserver:
                image: ${{ secrets.DOCKER_USERNAME }}/techbuddy:latest
                command: node peerServer.js
                ports:
                  - "9000:9000"

              db:
                image: postgres:latest
                environment:
                  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                  POSTGRES_DB: techbuddy
                volumes:
                  - pgdata:/var/lib/postgresql/data
                ports:
                  - "5432:5432"

              nginx:
                image: nginx:latest
                volumes:
                  - ./nginx.conf:/etc/nginx/nginx.conf
                  - /etc/nginx/ssl:/etc/nginx/certs
                ports:
                  - "80:80"
                  - "443:443"
                depends_on:
                  - web
                  - websocket
                  - peerserver

            volumes:
              pgdata:' > docker-compose.prod.yml

            # Stop and remove existing containers
            docker-compose -f docker-compose.prod.yml down

            # Start new containers
            docker-compose -f docker-compose.prod.yml up -d

            # Clear docker
            docker system prune -f
